# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

title: Welcome to CtrlReturn
email: ctrlreturn@riseup.net
description: > # this means to ignore newlines until "baseurl:"
  Dive into the intersection of music and Python at ctrlreturn.de
  Berlin's ultimate live coding event. Experience real-time music creation,
  workshops, and the unique vibes of our vibrant community.
  Unleash your creativity with Python programming like never before.
  Join us for a tech-meets-music adventure!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ctrlreturn.de" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: CtrlReturn
github_username:  CtrlReturn

# Build settings
permalink: none
markdown: kramdown
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
