- icon: "ion-headphone"
  title: "Live-Coding Audio"
  content: Using Software e.g. FoxDot/Renardo, Tidal Cycles, SonicPi, or SuperCollider to compose music

- icon: "ion-image"
  title: "Live-Coding Visuals"
  content: Create interactive video loops and visual compositions with software e.g. Hydra

- icon: "ion-earth"
  title: "Together in real-time"
  content: Collaborative jamming IRL or online using Troop or Flok

- icon: "icon ion-coffee"
  title: "Networking"
  content: As Newbie or Expert, this is a good opportunity to share your passion with others
